# GitHub Action: whenever creating a new release of the source code,
# also create a release of the installable plugin.
# Steps to execute:
# - Checkout the source code
# - Run "npm install" to download all npm dependencies under node_modules/
# - Build project using internal build process
# - Create a .zip file, excluding hidden and build-process files
# - Upload the .zip file as an artifact to the action (this results in a double-zipped file)
# - Upload the .zip file as a release, for download
name: Generate Installable Theme and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bahmutov/npm-install@v1
    - run: |
        npm run build
    - run: |
        npm run export
    - uses: actions/upload-artifact@v2
      with:
        name: ankur
        path: build/ankur.zip
    - uses: JasonEtco/upload-to-release@master
      with:
        args: build/ankur.zip application/zip
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
